### PR TITLE
Add yarn to readme

### PR DESCRIPTION
**Pull request by SaraVieira**

### CODE REVIEW

**Comment by thangngoc89** [comment]
We should automate this process

**Comment by reznord** [comment]
merging after it passes all the CI tests?

**Comment by thangngoc89** [comment]
No, automate the generation of cli command result in README to avoid PR like this one.

https://github.com/DavidWells/markdown-magic

**Comment by lukeed** [comment]
Lol, luckily I think we're done with flags 😉

**Comment by reznord** [comment]
We are waay far from "done with flags" :P

**Pull request merged**
