### PR TITLE
fix - Add .ds_store to ignore in sw-precache

### PR DESCRIPTION
**Pull request by SaraVieira**
Fixes weird error where sw-precache was adding .DS_Store to sw.js

screenshot 2017-07-31 00 16 52

### CODE REVIEW

**Comment by lukeed** [comment]
Oh shoot 😟 Looks like your built-in linter auto-saved haha

**Comment by SaraVieira** [comment]
Damn prettier and me refusing to shut it off :(

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SaraVieira** [comment]
I'll undo the prettier tomorrow 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lukeed** [comment]
Lol 😆 Thanks!

**Comment by thangngoc89** [comment]
@SaraVieira I feel your pain. Had to disable prettier globally and enable it for each project

**Comment by developit** [comment]
Think it would be worth ignoring all dotfiles?

**Comment by lukeed** [comment]
@developit I thought so too (`/^[.]/`) but @SaraVieira pointed out that it'd block temp directories too, like `.tmp`, should anyone ever setup an in-between step.

**Comment by SaraVieira** [comment]
@lukeed @developit @thangngoc89 All fixed 👍

**Pull request merged**
