### PR TITLE
Add size-plugin

### PR DESCRIPTION
**Pull request by developit**
**What kind of change does this PR introduce?**

Adds [size-plugin](https://github.com/GoogleChromeLabs/size-plugin) for pretty output size tracking & display.

### CODE REVIEW

**Comment by developit** [comment]
CI failure was a Node 8 requirement, bumping the build to get a new version of size-plugin that polyfills.

**Comment by ForsakenHarmony** [comment]
pretty sure it's still the certificate problem thing

**Comment by developit** [comment]
might do.

**Comment by reznord** [comment]
Won't git cry about the history if we do that?

**Comment by reznord** [comment]
Closing this in favour of https://github.com/developit/preact-cli/pull/630

**Pull request closed without merging**
