### PR TITLE
feat(cli): Add size-plugin

### PR DESCRIPTION
**Pull request by reznord**
**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
No

**Summary**
Adds [size-plugin](https://github.com/GoogleChromeLabs/size-plugin) for pretty output size tracking & display.

screen shot 2018-09-07 at 6 51 57 pm

(the same PR as https://github.com/developit/preact-cli/pull/624, raised on `next` branch, just so that the commit log doesn't get messy)

### CODE REVIEW

**Comment by prateekbh** [comment]
can you post a pic with --esm flag as well?

**Comment by reznord** [comment]
@prateekbh with `--esm` flag during build

screen shot 2018-09-07 at 10 56 03 pm

**Comment by prateekbh** [comment]
@developit anyway we can sort this `alphabetically` so everything is comparable to each other?

**Comment by prateekbh** [comment]
any reason we're holding this off?

**Pull request merged**
