### PR TITLE
Fix multiple copies of preact in production build (fix #126)

### LINKED ISSUE #126: Production build includes two copies of preact?
### Steps to reproduce:

1. `npm install -g preact-cli`
2. `preact create <app>`
3. `cd <app>`
4. `preact build --json`
5. Inspect `stats.json` using a Webpack stats analyzer (this one is from `webpack-bundle-analyzer`):

image

### Expected behavior:

The preact library should only be included once in `bundle.js`.

### Actual behavior:

It is included twice.

### PR DESCRIPTION
**Pull request by reznord**
Fix for #126

### CODE REVIEW

**Comment by rkostrzewski** [comment]
Travis build failed because we Skip installation of dependencies in tests. I'll look into enabling it & caching.

**Comment by reznord** [comment]
@rkostrzewski the tests failed in my local machine as well. Can you please have a look at the log? 

https://paste.fedoraproject.org/paste/~djRyBcRUltRzRRaON3~qg

**Comment by developit** [comment]
I wonder if falling back to `require.resolve()` if the file doesn't exist would work here

**Comment by reznord** [comment]
not sure how that is gonna fit in. Can you tell me how to get this problem fixed?

**Comment by lukeed** [comment]
I think we just need to provide a path to the dev/module bundle? We can do this at the top of the config... something like:

```js
let preact, type = isProd ? 'preact/dist/preact.min' : 'preact';

try {
  preact = require.resolve(type);
} catch (err) {
  throw err;
}

// ...

preact$: preact
```

Also, this is because I'm suspecting that `env.cwd` isn't being set correctly. 

---

Not able to go thru this right now & debug what's happening, else I would! 😄

**Comment by rkostrzewski** [comment]
Nah, tests just skip `npm install` step to be faster. 

@reznord the easiest way is to remove `--no-install` from [here](https://github.com/developit/preact-cli/blob/master/tests/lib/cli.js#L13) tough I'm afraid timeout will occur. I'll tinker around this tomorrow hopefully.

**Comment by reznord** [comment]
Can't we use yarn? It is much faster compared to npm. I know this is just going towards #15 😅

**Comment by rkostrzewski** [comment]
More like #31 😃

**Comment by reznord** [comment]
yeah !!

**Comment by reznord** [comment]
@rkostrzewski the suggestion by @lukeed works perfectly fine. Though that is more like a hack. If it is fine, I'll make another PR to the same with the patch by @lukeed.

I hope that will be fine.

**Comment by developit** [comment]
Suggestion - we can use [require-relative]() for this:

```js
import requireRelative from 'require-relative';

// attempt to resolve a dependency, giving $CWD/node_modules priority:
function resolveDev(dep, cwd) {
  try { return requireRelative.resolve(dep, cwd || process.cwd()); } catch (e) {}
  try { return require.resolve(dep); } catch (e) {}
  return dep;
}

// ...
aliases: {
  preact$: resolveDep(isProd ? 'preact/dist/preact.min' : 'preact', env.cwd),
}
```

**Comment by lukeed** [comment]
Yeah, we can. Is there a benefit here though? Plus I still have a feeling that `env.cwd` isn't set correctly

**Comment by developit** [comment]
Hmm. If `env.cwd` isn't set, a lot of things should be blowing up. It should point to the directory where preact-cli was spawned, or the custom directory passed to the CLI in the case of tests and whatnot ([ref](https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L48)).

The reason I suggested require-relative is so that if someone installs a specific version of `preact` or `preact-compat`, they'll get that version.  I want to avoid people being stuck with whatever version we happened to ship with `preact-cli`.  We'll want to take that into account when doing prerendering too - currently that uses the one we ship with as well.

**Comment by lukeed** [comment]
Yeah, that's what I thought, but was having doubts looking at the travis logs here.

I agree. But in a Node 6+ environment, it's flat dep tree, so wouldn't a custom install overwrite what we ship? I'm inclined to think it does, since it's the same name (as opposed to a unique dep), but today also seems to be "just one of those days". 😴 😇

**Comment by developit** [comment]
`npm link` creates non-flat trees, I actually think that might have been what @reznord was seeing originally.

**Comment by reznord** [comment]
when I run `npm run test` it is opening up `Google Chrome Canary`. Any idea why that is happening?

**Comment by reznord** [comment]
In the travis log, this kinda caught my mind (https://travis-ci.org/developit/preact-cli/jobs/246455525#L1827) any idea why there are two instances of that?

**Comment by rkostrzewski** [comment]
@reznord it's opening Google Chrome because tests use it to verify if the app works correctly :smile:. As for the warning with AudioManager - it doesn't matter at all (folks at lighthouse have that warning too).

**Comment by reznord** [comment]
@rkostrzewski cool. I have updated the PR. Can you please review it? As @developit suggested, I have added the `require-resolve` module and got it working.

**Pull request merged**
