### PR TITLE
move html-webpack-exclude-assets-plugin to dependencies

### PR DESCRIPTION
**Pull request by hassanbazzi**
Fixes https://github.com/developit/preact-cli/issues/148

### CODE REVIEW

**Comment by lukeed** [comment]
Should be a quick 1.2.1

**Comment by reznord** [comment]
Approved even before tests succeeded  :P

**Comment by hassanbazzi** [comment]
Tests have been sparodically failing. :(

**Comment by reznord** [comment]
@hassanbazzi it is just failing on node6.x test. Rest all succeded.

**Comment by hassanbazzi** [comment]
That's also sparodic. :D

**Comment by reznord** [comment]
Well, I restarted the job, and now it is working fine !!

**Comment by reznord** [comment]
Travis has some issues I guess, not sure though, I had to restart twice for the last test.

Then it worked.

**Comment by reznord** [comment]
@hassanbazzi merged :)

**Pull request merged**
