### PR TITLE
temporarily bypass async loader for preact x

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by prateekbh** [comment]
But wouldn't this disable coffee splitting?

**Comment by reznord** [comment]
In `Preact X`, yes it will disable code splitting

**Comment by developit** [comment]
I don't think it's a good idea to ship code splitting in a disabled state.

**Comment by prateekbh** [comment]
+1 ^

**Comment by ForsakenHarmony** [comment]
Was meant as a temporary workaround so people can use preact cli with x until it's fixed

**Comment by developit** [comment]
one option here would be to remove the base reuse stuff and just have the async loader's component render null while waiting. It'd just have the flash of no content problem we had before @lukeed's fix, but still async/lazy.

**Comment by prateekbh** [comment]
Which works but still is ugly 😐

**Comment by developit** [comment]
Indeed. I spent a few hours playing around with using componentDidCatch for this, but I'm running into some alpha.2 bugs.

**Comment by ForsakenHarmony** [comment]
I've been using `yarn link` a bunch recently for testing

**Comment by developit** [comment]
that's my usual approach yeah.

**Comment by reznord** [comment]
I think @developit has a PR on the way for async component in Preact X.

**Pull request closed without merging**
