### PR TITLE
Style import fix

### PR DESCRIPTION
**Pull request by ethanroday**
Addresses #159.
Also changed spaces to tabs, as that seemed to be the convention.

### CODE REVIEW

**Comment by ethanroday** [comment]
This would be a breaking change for `.less` files, since providing `paths` to `less-loader` disables Webpack's `~` resolution. For `sass-loader`, though, this is not the case.
@developit I can just remove all of the tildes from `.less` files, but wanted to know if you think this is the right approach.

**Comment by developit** [comment]
Hmm - I've never used `less-loader` with the `path` option.   Does it fully bypass the built-in path handling in `less`?

**Comment by developit** [comment]
@lukeed I think that was my initial reaction too, though this is a lot of moving parts so I wasn't sure.  In the linked #159 issue it seemed like he was hoping to support importing `npm` modules from `.scss` files without using the `~` prefix.

**Comment by lukeed** [comment]
Ah right. I'm inclined to think that moving to `resolve.modules` will get picked up by `sass-loader` (didn't check). But if not, then leaving the `includePaths` will be fine.

The important part is not breaking `less-loader` behavior.

**Comment by reznord** [comment]
@lukeed @developit is this still valid?

**Comment by developit** [comment]
Crap, I botched that merge.

**Comment by lukeed** [comment]
We should also add `paths` to the `stylus-loader`, now that we have it.

**Pull request merged**
