### PR TITLE
Show child compilation errors

### PR DESCRIPTION
**Pull request by developit**
This will probably help show the error from #733. For me, it was that I didn't have one of my deps installed.

### CODE REVIEW

**Comment by prateekbh** [comment]
Nice...

**Comment by ForsakenHarmony** [comment]
lol why am I in that commit? 👀

**Comment by hassanbazzi** [comment]
One does not choose when they are summoned, but one must be ready, and you were.

**Comment by psabharwal123** [comment]
@developit in code below forEach passes index as 2nd param to callback warn, warn's second param is exit code so build will fail if there is more than 1 warning which i think it should not. Also same issue in forEach(error), few lines above

```
allFields(stats, 'warnings')
			.map(stripLoaderPrefix)
			.forEach(warn);
```
should be 
```
allFields(stats, 'warnings')
			.map(stripLoaderPrefix)
			.forEach(msg => warn(msg));
```

**Comment by ForsakenHarmony** [comment]
ja🅱️ascript

**Pull request merged**
