### PR TITLE
Flag to enable react hot loader with default set to false

### PR DESCRIPTION
**Pull request by psabharwal123**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
no, updated README file

**Summary**
fixes https://github.com/developit/preact-cli/issues/722

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
The babel plugin is missing 

https://github.com/developit/preact-cli/blob/next/packages/cli/lib/lib/babel-config.js#L30

**Comment by psabharwal123** [comment]
Do you mean I should add '&& env.rhl' in that line?

**Comment by ForsakenHarmony** [comment]
probably

**Comment by ForsakenHarmony** [comment]
thx

**Pull request merged**
