### PR TITLE
Add preact-cli-lodash to Readme.md

### PR DESCRIPTION
**Pull request by SaraVieira**
Freshly created the first plugin , any feedback would be awesome

https://www.npmjs.com/package/preact-cli-lodash

cc @prateekbh @developit @reznord @rkostrzewski

### CODE REVIEW

**Comment by developit** [comment]
amaze

**Comment by developit** [comment]
I think the plugin is missing a build script though, I don't see a lib/dist/whatever folder in the package:
https://unpkg.com/preact-cli-lodash@1.0.1/

I see babel is in the deps, so maybe its just missing `"build": "babel src -d lib"` and `"main": "lib"`?

**Comment by SaraVieira** [comment]
That script existed but I removed it since the preact config supports es6.

Why do you think it would be good to have it @developit?

**Comment by developit** [comment]
Doesn't entirely need it, but the `src` directory is missing too - there's no code in the package right now haha

**Comment by SaraVieira** [comment]
Effing npm ignore that comes by default -.-

**Comment by developit** [comment]
haha yeah. I've stopped using npmignore in favor of `"files"` in the package.json

**Comment by SaraVieira** [comment]
@developit updated , sorry 😢 

https://unpkg.com/preact-cli-lodash@1.1.0/

**Comment by SaraVieira** [comment]
Can I add this one too : https://github.com/SaraVieira/preact-cli-postcss ?

**Comment by reznord** [comment]
Doesn't makes sense to me !!

IMO, no one is going to have a look at the plugins until they need. Instead of putting the documentation for plugins in the main README, it is better to add a separate page `plugins.md` and add all those in that. 

This way the README stays clean too !!

**Comment by SaraVieira** [comment]
Dude I think that's is totally fine, I don't know if you are yelling but it sounds like you are and there is no need for that. 

This was just a proposal, I can create a plugins.md. 

I was just trying to help dude

**Comment by developit** [comment]
I'm fine with either, or maybe we keep the Plugins heading in the readme but point to a Wiki page that lists them?

I created the page and added both plugins 🎉
https://github.com/developit/preact-cli/wiki/Plugins

**Comment by SaraVieira** [comment]
@developit @reznord Updated the Readme to just point to the wiki page 👍

**Comment by reznord** [comment]
Cool, now I guess we can add [preact-cli-postcss](https://github.com/SaraVieira/preact-cli-postcss) plugin too. 😄

**Comment by SaraVieira** [comment]
@developit Already added it to the page 😄

**Comment by rkostrzewski** [comment]
@developit @reznord @SaraVieira should I add to `Plugins` section of `README.md` what's to come (doing `preact build --plugins lodash,postcss,awesome` and `plugins` section in `package.json`) ? Looks kinda empty right now 😛 

Also @developit @reznord also thinking about doing two things exposing `webpackHelpers` from `preact-cli` npm module and exposing `createWebpackConfig` so that plugins could be used as such
```
import awesome from 'preact-cli-plugin-awesome'

export default config => {
   awesome(config)
}
```

and  the plugin would look like this:
```
import { webpackHelpers } from 'preact-cli'

export default config => {
  let loaderWrapper = webackHelpers.getLoadersByName('some-loader')[0]
  ...do awesome stuff...
}
```

and exporting sth like `createWebpackConfig` so users can do sth like this when developing:

```
const createWebpackConfig = require('preact-cli'). createWebpackConfig

let env = { cwd: '.', ... }
let config = createWebpackConfig(env)
debugger;
console.log(createWebpackConfig)
```
when developing plugins & that would be useful for stuff like `eslint-plugin-import` or `storybook` (each requires `webpack.config.js` to work properly with `preact-cli`)

**Comment by prateekbh** [comment]
@rkostrzewski the syntax
```
webackHelpers.getLoadersByName/getPluginByName('some-loader')[0]
``` 
looks great 👍 

just a small thing 
```
export default config => {
   awesome(config)
}
```

⬆️ should have a return statement to keep things clearer

**Comment by SaraVieira** [comment]
@rkostrzewski That sounds like a great idea and yes filling that page would be awesome 👍

**Comment by SaraVieira** [comment]
@rkostrzewski thanks man! 

Is everyone okay with merging this? 🙌

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by developit** [comment]
All good!

**Comment by SaraVieira** [comment]
🎉🍕

**Pull request merged**
