### PR TITLE
Resolve 0.0.0.0 to windows in localhost

### PR DESCRIPTION
**Pull request by reznord**
I hope this resolves the `0.0.0.0` issue in windows.

### CODE REVIEW

**Comment by yavorski** [comment]
LGTM

**Comment by reznord** [comment]
Tested on windows too 😄.

**Comment by thangngoc89** [comment]
No. This would break many things, especially accessing the site in local network (aka testing in another device). You can just listen to 0.0.0.0 and print to console `localhost`

**Comment by reznord** [comment]
With this you can listen on `0.0.0.0` too

**Pull request merged**
