### PR TITLE
Fix typo in `npm run serve --server`

### PR DESCRIPTION
**Pull request by DanielApt**
**What kind of change does this PR introduce?**

Changed 
`npm run serve -- --server config` to
`npm run serve --server config` in README.md

**Did you add tests for your changes?**
Not needed.

**Summary**
Remove typo from README.md

**Does this PR introduce a breaking change?**
No.

**Other information**
Not needed.

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
Does this work with npm now? I know it does with yarn

**Comment by lukeed** [comment]
Tested a series of `npm run *` commands in `6.1` and `6.3` versions of `npm`, the `--` spacer is still needed.

**Comment by developit** [comment]
Apologies, I merged this in error. `npm run server -- --server config` is still correct.

**Comment by lukeed** [comment]
You are forgiven.

**Comment by reznord** [comment]
Reverting this back since that doesn't work.

**Pull request merged**
