### PR TITLE
fix the error where c.getModules is not a function

### PR DESCRIPTION
**Pull request by manjula91**
**What kind of change does this PR introduce?**

It fixes the preact build --json fails with `TypeError: c.getModules is not a function`

https://github.com/developit/preact-cli/issues/467

**Other information**

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
Already fixed, also you converted all the tabs to whitespace

**Comment by reznord** [comment]
A bit late! but thanks 😄

**Comment by manjula91** [comment]
shit shit why am I late :(

**Comment by ForsakenHarmony** [comment]
Jason is just too fast 🙈

**Pull request closed without merging**
