### PR TITLE
fix prerender and webpackconfig for custom directories in npm modules

### LINKED ISSUE #42: Build error with preact-material-components
Hello,

Linking a component from preact-material-components works like a charm in dev mode but when trying to build for production it fails.

**Steps to reproduce**

1) preact create test
2) cd test
3) npm install --save preact-material-components
4) edit routes/home/index.js
5) paste this code :

```js
import { h, Component } from 'preact'
import style from './style'

import FormField from 'preact-material-components/FormField'
import Radio from 'preact-material-components/Radio'

import 'preact-material-components/FormField/style.css'
import 'preact-material-components/Radio/style.css'


export default class Home extends Component {
  render() {
    return (
      <div class={style.home}>
        <h1>Home</h1>
        <FormField>
          <Radio id="r1" name='opts'></Radio>
          <label for="r1">Radio 1</label>
          <Radio id="r2" name='opts'></Radio>
          <label for="r2">Radio 2</label>
        </FormField>
      </div>
    )
  }
}
```

=> npm start : **OK**

=> npm run build : **Fails**

```
Template execution failed: SyntaxError: Unexpected token import
  Error: /Users/cedric/Desktop/test/node_modules/preact-material-components/FormField/index.js:1
  (function (exports, require, module, __filename, __dirname) { import { h } from "preact";
                                                                ^^^^^^
  SyntaxError: Unexpected token import
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [test]/[babel-register]/lib/node.js:152:7
  
  - module.js:20 require
    internal/module.js:20:19
  
  - index.js:4 Object.<anonymous>
    /Users/cedric/Desktop/test/routes/home/index.js:4:1
  
  - node.js:144 loader
    [test]/[babel-register]/lib/node.js:144:5
  
  - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [test]/[babel-register]/lib/node.js:154:7
  
  - module.js:20 require
    internal/module.js:20:19
  
  - index.js:7 Object.<anonymous>
    /Users/cedric/Desktop/test/index.js:7:1
  
  - node.js:144 loader
    [test]/[babel-register]/lib/node.js:144:5
```

Any idea ?

### PR DESCRIPTION
**Pull request by prateekbh**
Fixes #42 
This fixes inclusion of custom directories from `node modules`.
Also this means `preact-material-components` can now be used separately, without the entire package

### CODE REVIEW

**Comment by prateekbh** [comment]
@lukeed @developit it is a WIP, as I have a working stuff, but it no more uses babel create config

**Comment by prateekbh** [comment]
@developit @lukeed added a dummy travis yml to make travis happy

**Comment by prateekbh** [comment]
>How does this work now that the include function has been removed? Are all node_modules processed by default? 

Yes

>Unless I'm missing something obvious, doesn't seem like the module and/or jsnext:main entries will be picked up.

`webpack` picks `node_modules` in the order module -> js:next(i guess) -> main -> ...
so it will still be picked up

>Also, can remove the @webpack-blocks/babel from package.json. 👍
sure will do

>Oh, and I'm pretty sure ignore:false operates the same as its default (ignore:null). So that can probably be removed.
by default it is `ignore: true` so `ignore: flase` is needed

**Comment by prateekbh** [comment]
@lukeed i have made changes to the package.json

**Comment by lukeed** [comment]
Hmmm interesting. I'm seeing `ignore:null` [here](http://babeljs.io/docs/usage/api/#options). 

Also, the regex can be `/\.jsx?$/`.

Looks good~!

**Comment by prateekbh** [comment]
@lukeed aren't you talking about `ignores: null` in prerender? Which is actually this
https://github.com/babel/babel/tree/master/packages/babel-register#ignores-node_modules-by-default

**Comment by lukeed** [comment]
Oohhh... that's probably why I got stuck in my attempt! Thanks!

**Comment by prateekbh** [comment]
Also @lukeed, i guess regex should be both. As node modules can be js as well. What say?

**Comment by lukeed** [comment]
The `?` applies to the character before in this case, so `.js` and `.jsx` files will both work. It's also the "standard" regex `test` that I see.

```js
/\.jsx?$/.test('foo.js')l
//=> true

/\.jsx?$/.test('foo.jsx')
//=> true
```

**Comment by prateekbh** [comment]
@lukeed fixed the regex :)

**Comment by prateekbh** [comment]
@developit need approval if all looks good.

**Comment by prateekbh** [comment]
awaiting response/approvals here, lemme know if more work is needed here

**Comment by developit** [comment]
Hmm - I know I missed approving this, but can we double-check the removal of jsnext `include()`?  In my experience this breaks ES5 modules since it rewrites them into strict mode - some modules assume the global context to be `window`, and when loaded via Babel it's `undefined`.

**Comment by prateekbh** [comment]
@developit can you point me to some such modules?

**Comment by developit** [comment]
Might be hard, only saw the issue in an internal project and it was ages ago.

For my own sake, how come the check for `jsnext:main` / `modules` was failing for `preact-material-components`?

**Comment by prateekbh** [comment]
because for that repo, I suggest to include separate files instead of the whole repo as tree shaking is not yet perfect

**Comment by lukeed** [comment]
It was because the `preact-material-components`'s `module` entry points (and _can only_ point) to a single `index.js` that looked (roughly) like this:

```js
import Foo from './foo';
import Bar from './bar';
export { Foo, Bar }
```

This introduces the imperfect tree-shaking (nothing we can do, everything gets `import`ed due to the declaration), so @prateekbh recommended nested-file imports.

However, the `include()` fn we had only respects the `index.js` file because `preact-material-components` is the module name, and not `preact-material-components/foo`.

---

On second thought, I think the `include` function _could_ have stayed, but it wouldn't make a difference. The main reason this PR fixes #42 is because of `ignore:false`, which was ignoring all of `node_modules` by default.

It wouldn't have made a difference because `ignore:false` passes everything thru `babel-loader` (pros vs cons), which precludes the `jsnext:main`|`module` entries.

**Comment by prateekbh** [comment]
@lukeed only `ignore:false` was still throwing error, i tried doing both separately, seems both are needed

**Comment by lukeed** [comment]
Ah, okay. I guess `include` takes a higher priority. Thanks

**Comment by developit** [comment]
It just seems odd the include() wouldn't have seen the `module` key within `node_modules/preact-material-components/package.json` and triggered Babel.  Maybe I'm crazy :P

**Comment by prateekbh** [comment]
@developit  If i include components like

`import Toolbar from 'preact-material-components/Toolbar` 

instead of 

`import {Toolbar} from 'preact-material-components` 

do you think it would have worked?

**Comment by lukeed** [comment]
I would have expected it to, yes, but in my trials (using a different set of changes), it did not work for the reasons I mentioned above: _only_ `preact-material-components/index.js` was transformed correctly.

**Pull request merged**
