### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by KadoBOT**

### CODE REVIEW

**Comment by reznord** [comment]
Cancelling the build, since for README changes, not necessary to do a whole build on Travis :P

**Comment by prateekbh** [comment]
@reznord can we not tell travis to NOT run the test for certain file changes?

**Comment by thangngoc89** [comment]
@prateekbh we can't do it automatically. But we can add [skip ci] to commit message for that purpose

**Comment by reznord** [comment]
well there is a open issue on this - https://github.com/travis-ci/travis-ci/issues/6301

**Pull request merged**
