### PR TITLE
resolved conflicts :feature/webpack3

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**

### CODE REVIEW

**Comment by reznord** [comment]
Closing this PR since there is already one open for the same.

**Comment by kuldeepkeshwar** [comment]
@reznord 
It was for `feature/webpack3` branch as it has fix conflicts :-)

**Comment by reznord** [comment]
I did it already ;) that's why closed this. Will be pushing the PR soon

**Comment by kuldeepkeshwar** [comment]
Oh!!!!!  great 👍

**Pull request closed without merging**
